### ISSUE TITLE
Build fails with latest setuptools

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/PyMFEM#114]
With setuptools v60.0.3
Python 3.7 and 3.8 fails with this
```
ImportError: cannot import name 'sdist' from 'setuptools._distutils.command' 
```
Python 3.9 fails with 
```
 Traceback (most recent call last):
    File "/root/PyMFEM/mfem/_ser/setup.py", line 22, in <module>
      from distutils.core import *
    File "/usr/local/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 92, in create_module
      return importlib.import_module('setuptools._distutils')
    File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 16, in <module>
      import setuptools.version
    File "/usr/local/lib/python3.9/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 33, in <module>
      import email.parser
    File "/usr/local/lib/python3.9/email/parser.py", line 12, in <module>
      from email.feedparser import FeedParser, BytesFeedParser
    File "/usr/local/lib/python3.9/email/feedparser.py", line 27, in <module>
      from email._policybase import compat32
    File "/usr/local/lib/python3.9/email/_policybase.py", line 9, in <module>
      from email.utils import _has_surrogates
    File "/usr/local/lib/python3.9/email/utils.py", line 29, in <module>
      import socket
    File "/usr/local/lib/python3.9/socket.py", line 548, in <module>
      import array
    File "/root/PyMFEM/mfem/_ser/array.py", line 15, in <module>
      import _array
  ModuleNotFoundError: No module named '_array'

```

**Comment by sshiraiwa** [comment]
Fixed (#112)
