### ISSUE TITLE
Compilation error: rpath are broken

### ISSUE THREAD

**Issue by tbridel** [mfem/PyMFEM#147]
Hello everyone,

I am on a Darwin platform with the apple M1 CPU and for other reasons I have to stick with the compiler suite by `llvm` and the interface of `open-mpi` for parallelism - as for versions, they are as follow:

```bash
Homebrew clang version 15.0.1
Target: arm64-apple-darwin21.5.0
```

```bash
==> open-mpi: stable 4.1.4 (bottled), HEAD
High performance message passing library
https://www.open-mpi.org/
/opt/homebrew/Cellar/open-mpi/4.1.4_2 (758 files, 17.6MB) *
```

I am trying to compile PyMFEM with pre-installed MFEM, HYPRE & METIS v5.1.0 distributions.
MFEM is installed with the following options:

```bash
${CMAKE} \
-DMFEM_USE_MPI=YES -DMFEM_MPI_NP=2 -DMFEM_USE_OPENMP=YES \
-DHYPRE_DIR=${CODE_DIR}/${SUB_DIR}/hypre/src/hypre \
-DMETIS_DIR=${CODE_DIR}/${SUB_DIR}/metis-${METIS_VERSION}/build \
-DMETIS_INCLUDE_DIRS=${CODE_DIR}/${SUB_DIR}/metis-${METIS_VERSION}/build/include \
-DMETIS_LIBRARIES=${METIS_LIBRARIES} \
-DMFEM_USE_METIS_5=TRUE \
-DCMAKE_CXX_COMPILER=${CXX} \
-DMPI_CXX_COMPILER=${MPICXX} \
-DBUILD_SHARED_LIBS=ON \
${@} \
-S .. -B .
```

I have had a **lot** of trouble with the build and the install of PyMFEM -- actually, truth be told, I started 2 days ago and for now it is still not working.
The only way I managed to get it running till the end is with the following command:

```bash
python3 setup.py install --no-serial --with-parallel --mfem-prefix=<absolute/path/to>/mfem/build --mfem-source=<absolute/path/to>//mfem --CXX=/opt/homebrew/opt/llvm/bin/clang++ --CC=/opt/homebrew/opt/llvm/bin/clang --MPICXX=/opt/homebrew/opt/open-mpi/bin/mpicxx --MPICC=/opt/homebrew/opt/open-mpi/bin/mpicc --hypre-prefix=<absolute/path/to>//hypre/src/cmbuild --metis-prefix=<absolute/path/to>/metis-5.1.0/build
```

along with the following modifications of PyMFEM source code:

```python
# mfem/_ser/setup.py
...
include_dirs = [mfemserbuilddir, mfemserincdir, mfemsrcdir, numpyinc, hypreinc, metisinc,]
library_dirs = [mfemserlnkdir, hyprelib, metis5lib,]
...
```

```Makefile
# Makefile
...
HYPRELNKFLAG = -L$(HYPRELIB) -lHYPRE
METISINCFLAG = -I$(METISINC)
METISLNKFLAG = -L$(METISLIB) -lmetis
#MPIINCFLAG  = -I$(MPIINC)
...
```

```Makefile
# mfem/_ser/Makefile
...
%_wrap.cxx: %.i
	$(SWIG) -I$(MFEMSERBUILDDIR) $(SWIGFLAG) $(MFEMSERINCFLAG) $(HYPREINCFLAG) $(METISINCFLAG) $<
...
```

```Makefile
# mfem/_par/Makefile
...
%_wrap.cxx: %.i
	$(SWIG) -I$(MFEMBUILDDIR) $(SWIGFLAG) $(MPI4PYINCFLAG) $(MFEMINCFLAG) $(HYPREINCFLAG) $(METISINCFLAG) -I$(STRUMPACK_INCLUDE) $<
...
```

With all this, the build process finishes correctly, and then the install finishes as well.
But !
The `rpath` in the libraries are all wrong, making the whole installed package unusable ... Here is an example for `_std_vectors.cpython-310-darwin.so` (arbitrary, same problem occurs for all of the `*.so`):

```bash
# otool -L _std_vectors.cpython-310-darwin.so
_std_vectors.cpython-310-darwin.so:
	/usr/local/lib/libmfem.4.4.1.dylib (compatibility version 4.4.1, current version 4.4.1)
	@rpath/libHYPRE.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libmetis.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/open-mpi/lib/libmpi.40.dylib (compatibility version 71.0.0, current version 71.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

The first, second and third lines should point to the libraries I specified in the `python3 setup.py install ...` command (see above). And actually during the link, the command executed shows the right `-L` and `-Wl,-rpath,` annotations:

```bash
/opt/homebrew/opt/open-mpi/bin/mpicxx -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-arm64-cpython-310/std_vectors_wrap.o -L<absolute/path/to>/mfem/build/lib -L<absolute/path/to>/hypre/src/cmbuild/lib -L<absolute/path/to>/metis-5.1.0/build/lib -Wl,-rpath,<absolute/path/to>/mfem/build/lib -Wl,-rpath,<absolute/path/to>/hypre/src/cmbuild/lib -Wl,-rpath,<absolute/path/to>/metis-5.1.0/build/lib -lmfem -lHYPRE -lmetis -o build/lib.macosx-12-arm64-cpython-310/_std_vectors.cpython-310-darwin.so
```

So the link command is right, but somehow the `rpath` do not make it to the library object itself. 
Could you please advise, I direly need this MFEM wrapper by the middle of the week ... ?

Thank you everyone & take care !

**Comment by tbridel** [comment]
Update: I tried the `next` branch, and things don't go to the end altogether.

Is there a (strong) dependency on `setuptools` @sshiraiwa ?

**Comment by sshiraiwa** [comment]
@tbridel, I feel to hear having a lot of trouble. I haven't checked with M1 Mac environment. Mac tend to do
something special with run environment, and something can be broken. The second error, however, looks
strange. To be sure, I just test it using a clean docker Python 3.10 image and it does run w/o an error. 
```
sudo docker run -it python:3.10 bash
# git clone https://github.com/mfem/PyMFEM.git
# cd PyMFEM
# git checkout next
# pip install SWIG cmake six
# pip install numba-scipy (<== install numpy, scipy, numba all together)
# python3 setup.py install --mfem-branch=master
# cd test
# python run_examples.py -serial -verbose
```
Although it is not Mac, I don't see why/how it errors like "mfem/__init__.py is not found". The function 
version is evaluated at the very early part of setup script. Do you have any idea?

**Comment by tbridel** [comment]
Hi @sshiraiwa !

Thank you very much for your coming back to me :)

- [x] I had not tried on a separate docker indeed: I have the same results as you,  the install goes well and the tests pass.
- [ ] Since you gave some specific package for the minimal python distribution you require, I tried with a virtualenv again, directly on the Mac this time.

```bash
virtualenv --setuptools 59.8.0 py3env # the setuptools version matches the one required by numba, it's redundant but one never knows !
source py3env/bin/activate
pip install SWIG cmake six
pip install numba-scipy
python3 setup.py install --mfem-branch=master # (this step hides a few steps actually: I run it once to clone mfem where it should be, then because of https://github.com/mfem/mfem/pull/3233 I have to modify `external/mfem/miniapps/performance/CMakeLists.txt`, and I comment lines 1609-1610 of pymfem `setup.py` to prevent it from cloning mfem again before running the command again)
```

This leads to the following crash/fault in the install, as before:

```
[100%] Built target miniapps
calling ... make install
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include/mfem -I/Users/tbridel/Documents/1-CODES/17-PyMFEM/external/mfem lininteg.i
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include/mfem -I/Users/tbridel/Documents/1-CODES/17-PyMFEM/external/mfem bilininteg.i
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_lininteg_ext.py
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_bilininteg_ext.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  F    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
ile "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
Traceback (most recent call last):
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    main_content = runpy.run_path(main_path,
    _fixup_main_from_path(data['init_main_from_path'])
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Vers    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
ions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
_main
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    prepare(preparation_data)
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
    exitcode = _main(fd, parent_sentinel)3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path

    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    return _run_module_code(code, init_globals, run_name,
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    exec(code, run_globals)
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 199, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    return _run_modu    'version': version(),
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 151, in version
    exec(code, run_globals)
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 199, in <module>
le_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    initfile_lines = open(VERSIONFILE, 'rt').readlines()
    _run_code(code, mod_globals, init_globals,
FileNotFoundError: [Errno 2] No such file or directory: 'mfem/__init__.py'
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    'version': version(),
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 151, in version
    return _run_module_code(code, init_globals, run_name,
....
```

and it goes on and on and one.

I agree with you, not finding `__init__.py` is impossible -- and it is there, and if I just ask  `os.path.isfile` it finds it.
I just noticed the first lines of the log mention the multiprocessing package though, I am investigating in this direction 🤷‍♂️  If you have any more ideas, I would be glad to hear them ! 😄

**Comment by tbridel** [comment]
Update regarding the `multiprocessing` remark above: it has nothing to do with it. Everywhere in `setup.py` where the `cpu.count()` was used, I hardcoded `1`, but it crashes in the same way:

```
[100%] Built target seqadiff
[100%] Built target miniapps
calling ... make install
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include/mfem -I/Users/tbridel/Documents/1-CODES/17-PyMFEM/external/mfem lininteg.i
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include -I/Users/tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include/mfem -I/Users/tbridel/Documents/1-CODES/17-PyMFEM/external/mfem bilininteg.i
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_lininteg_ext.py
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_bilininteg_ext.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 199, in <module>
    'version': version(),
  File "/Users/tbridel/Documents/1-CODES/17-PyMFEM/setup.py", line 151, in version
    initfile_lines = open(VERSIONFILE, 'rt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'mfem/__init__.py'
```

**Comment by tbridel** [comment]
Ok, here is an update regarding the `multiprocessing` investigation.
I commented everything in `setup.py` related to `multiprocessing`, and everytime there was a mapping to a `Pool` I wrote a good old for loop (I attach my `setup.py` so you can diff it). 
[setup.py.zip](https://github.com/mfem/PyMFEM/files/9698228/setup.py.zip)

Result is that now the install goes beyond

```bash
...
tbridel/Documents/1-CODES/py3env/lib/python3.10/site-packages/mfem/external/ser/include/mfem -I/Users/tbridel/Documents/1-CODES/17-PyMFEM/external/mfem bilininteg.i
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_lininteg_ext.py
calling ... /Users/tbridel/Documents/1-CODES/py3env/bin/python generate_bilininteg_ext.py
...
``` 

and finishes as expected ! ✌️ 🥳 

The tests pass too.

Could you by any chance push a fix so one can disable the multiprocessing capabilities with a flag ? If you are pretty busy right now, would you rather I push a PR ?

**Comment by sshiraiwa** [comment]
@tbridel Thank for your effort to narrow down the problem. I did a quick search to look for anything special in MacOS multiprocessing. I encountered this (https://www.reddit.com/r/learnpython/comments/g5372v/multiprocessing_with_fork_on_macos/) and this (https://youtrack.jetbrains.com/issue/PY-51409/Python-38-and-MacOS-multiprocessing-module-uses-spawn-as-default). 

Not fully sure yet this is relating But, the explanation here (https://docs.python.org/3.8/library/multiprocessing.html) makes me think adding 
```
multiprocessing.set_start_method("fork")
```
after import multiprocessing may solve this issue. Can you try this first to see if it changes the behavior?

Either way, happy to receive PR!

**Comment by tbridel** [comment]
Hi @sshiraiwa 👋 

You're right, good find ! Setting `multiprocessing.set_start_method("fork")` after the import does the trick and the install goes to the end successfully.

Maybe to keep it general, you could consider something in the lines of:

```python
import multiprocessing
from multiprocessing import Pool
# force fork instead of spawn on Mac OS to avoid race condition on mfem/__init__.py
import platform
if platform.system() == "Darwin":
    multiprocessing.set_start_method("fork")
```

?

Thank you for your help anyhow ;)

**Comment by sshiraiwa** [comment]
Wonderful. I did add the lines you suggested. 
I am hoping to get this branch to be merged in a week or so.  The main remaining task is
to update Github actions under .github.

**Comment by tbridel** [comment]
That sounds great, thanks ! 🥳
