### ISSUE TITLE
Power9 installation Failure

### ISSUE THREAD

**Issue by koparasy** [mfem/PyMFEM#187]
I am trying to install PyMFEM and it fails. 

`python setup.py install --with-parallel --CC=gcc --CXX=g++ --MPICC=mpicc --MPICXX=mpic++`

Outputs the following error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 314, in make_call
    raise subprocess.CalledProcessError(p.returncode,
subprocess.CalledProcessError: Command '/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/external/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/mpi4py/include dist_solver.i' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1881, in <module>
    main()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1877, in main
    run_setup()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1865, in run_setup
    setup(
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1662, in run
    _install.run(self)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/command/install.py", line 72, in run
    orig.install.run(self)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 605, in run
    self.run_command('build')
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1717, in run
    generate_wrapper()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/setup.py", line 1099, in generate_wrapper
    mp_pool.map(make_call, commands)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
subprocess.CalledProcessError: Command '/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/external/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/mpi4py/include dist_solver.i' returned non-zero exit status 1.
```

My configuration is the following
GCC: gcc@8.3.1
MPI: Spectrum MPI compiled with gcc@8.3.1
SWIG@4.0.2
python@3.10.2

**Comment by sshiraiwa** [comment]
Hi @koparasy 
This log is difficult to understand what is going on. Can you put --verbose option when calling setup.py
@Tzanio I don't have an access to a Power9 system. Can you recommend someone to help diagnosing this issue?

**Comment by koparasy** [comment]
Here is the output ([log.out.zip](https://github.com/mfem/PyMFEM/files/12070715/log.out.zip)) of the following command:

`python setup.py install --vv --with-parallel --CC=gcc --CXX=g++ --MPICC=mpicc --MPICXX=mpic++ 2> log.out 1>log.out`

The failed command is the following one:
`/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/external/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/mpi4py/include dist_solver.i`

When I find the dist_solver.i file and I execute the failing command I get the following:
```
[koparasy@lassen708:PyMFEM]$ find ./ -name dist_solver.i
./mfem/_par/dist_solver.i
[koparasy@lassen708:PyMFEM]$ pushd ./mfem/_par/

[koparasy@lassen708:_par]$ /usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/bin/swig -Wall -c++ -python -fastproxy -olddefs -keyword -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/par/include/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/external/mfem -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/python-envs/zero-ml-lassen/lib/python3.10/site-packages/mfem/external/include -I/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/mpi4py/include dist_solver.i

dist_solver.i:29: Error: Unable to find 'miniapps/common/dist_solver.hpp'
```

I hope this helps

**Comment by sshiraiwa** [comment]
Thank you.  Can you try this branch? 
   https://github.com/mfem/PyMFEM/tree/sha_update_after_distsolve
I think what is happening is that setup.py downloads a release version of MFEM. If that is the case, this PR should fix it.

**Comment by koparasy** [comment]
Alright, another error pops up. Attaching the logs : 
[py_mfem_build.log.zip](https://github.com/mfem/PyMFEM/files/12072825/py_mfem_build.log.zip)

**Comment by sshiraiwa** [comment]
Thank you. This is a puzzling error to me. The error message indicate that python is trying to import array module of PyMFEM, which should not happen, because array is one of modules setup.py is trying to build. And, this happens 
in a call-chain after ```from distutils.core import Extension, setup```

I tend to guess this is not Power 9 specific issue. But I am not sure what is going on. 
I wondered if this is due to the recent setuptools. However, I did run the command your are running in a plain docker python3.10 with setuptools 63.2 and 68.0. With both version, the build went through successfully and I was able to run ex1p.py. (68.0 is newest). As a side note, distutils in my environment is version 3.10.7. 

```
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/mfem/_ser/setup.py", line 13, in <module>
    from distutils.core import Extension, setup
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 92, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/lassen/lib/python3.10/site-packages/pkg_resources/__init__.py", line 33, in <module>
    import email.parser
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/.local/0.19/._lassen/djxhelnns567h6plfdxz2bvo4yyomgug/lib/python3.10/socket.py", line 549, in <module>
    import array
  File "/usr/WS1/zeroml/SoftwareStack/software-stack/tmp_py_mfem/PyMFEM/mfem/_ser/array.py", line 15, in <module>
    import _array
```

**Comment by koparasy** [comment]
Apparently I had a old setuptools 58.something. Upgrading it solved the installation issue.
