### ISSUE TITLE
build with external openblas

### ISSUE THREAD

**Issue by colmenaresj** [mfem/PyMFEM#211]
Hello, 
I was able to install PyMFEM with an external installation of MFEM, HYPRE and METIS 5. I am using GCC11.2 and MPICH 4.1.2 and OpenBLAS 0.3.24. Python 3.9

However, I am not able to run the examples. This is the error I get:
```
Traceback (most recent call last):
  File "/path/to/PyMFEM/examples/ex11p.py", line 33, in <module>
    import mfem.par as mfem
  File "/path/to/pymfem/lib/python3.9/site-packages/mfem/par.py", line 16, in <module>
    from  mfem._par.point import *
  File "/path/to/pymfem/lib/python3.9/site-packages/mfem/_par/point.py", line 10, in <module>
    from . import _point
ImportError:/path/to/pymfem/lib/python3.9/site-packages/mfem/_par/_point.cpython-39-x86_64-linux-gnu.so: undefined symbol: dpotrf_
```

I suspect it is because it is trying to link with `-llapack` or `-lblas` and in this case I need to use `-lopenblas` flags. I alreayd specified the `--blas-libraries=$OPENBLAS_DIR` and `--lapack-libraries=$OPENBLAS_DIR` flags during setup, where `$OPENBLAS_DIR` is the installation prefix (that contains `include/` and `lib/`).

Any suggestions on how to deal with this? My MFEM installation works properly, the issue is only with PyMFEM. This is what I have in my conda (mamba) environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mfem                      4.6.1.1                  pypi_0    pypi
mpi4py                    3.1.5                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.9.18          h0755675_1_cpython    conda-forge
python_abi                3.9                      4_cp39    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.12.0           py39h474f0d3_2    conda-forge
setuptools                69.1.0             pyhd8ed1ab_1    conda-forge
swig                      4.2.0                hc9a1274_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge

``

**Comment by v-dobrev** [comment]
Can you try using not just the path but full link flags, e.g. `--blas-libraries="-L$OPENBLAS_DIR/lib -lopenblas"` and similarly for `--lapack-libraries`? Make sure to check if your openblas install uses `lib` or `lib64` subdir and adjust the flags accordingly.

With this, if you get runtime error about not being able to find `libopenblas.so`, try adding also the flag `-Wl,-rpath,$OPENBLAS_DIR/lib` to `--blas-libraries` or `--lapack-libraries` (adding it to just one of them should be sufficient).

**Comment by colmenaresj** [comment]
Thanks for the reply! I had already the first approach and failed. I will try the second and let you know.

**Comment by colmenaresj** [comment]
The suggestion above did not work. I suspect I had multiple installations of OpenBLAS in my environment, since when I installed numpy using conda it also installed its own openblas, and this may have caused inconsistencies.

I will close this issue for now.
